#!/bin/bash
# /usr/local/bin/gpu

gpumode=$(/home/oli/.local/bin/gpumonitor)

case $1 in
    "opt")
	[ "$gpumode" != "HYB" ] &&
	    GTK_THEME=Arc-Dark-Custom zenity --question --icon="prime-hybrid" --width=200 --height=100 --title="Neustart nötig" --text="\nZum Hybridmodus umschalten? \n" &&
	    rog-mux -s optimus &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.disabled ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.rules /etc/udev/rules.d/00-remove-nvidia.disabled; } &&
	    xfce4-session-logout --reboot
	;;
    "int")
	[ "$gpumode" != "ECO" ] &&
	    GTK_THEME=Arc-Dark-Custom zenity --question --icon="amd-bajo" --width=200 --height=100 --title="Neustart nötig" --text="\nZum Ecomodus umschalten? \n" &&
            rog-mux -s optimus &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.rules ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.disabled /etc/udev/rules.d/00-remove-nvidia.rules; } &&
	    xfce4-session-logout --reboot
	;;
    "ult")
	[ "$gpumode" != "ULT" ] &&
	    GTK_THEME=Arc-Dark-Custom zenity --question --icon="prime-nvidia" --width=200 --height=100 --title="Neustart nötig" --text="\nZum Ultimate Modus umschalten? \n" &&
	    rog-mux -s ultimate &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.disabled ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.rules /etc/udev/rules.d/00-remove-nvidia.disabled; } &&
	    xfce4-session-logout --reboot
	;;
    *)
	echo "Parameters to choose are HYB|ECO|ULT"
	;;
esac
