#!/bin/bash
# /usr/local/bin/gpu

gpumode=$(/home/oli/.local/bin/gpumonitor)

case $1 in
    "opt")
	[ "$gpumode" != "HYB" ] &&
	    yad --title="MUX-Steuerung" --text="\n Zum Hybridmodus umschalten und neu starten? \n" &&
	    rog-mux -s optimus &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.disabled ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.rules /etc/udev/rules.d/00-remove-nvidia.disabled; } &&
	    xfce4-session-logout --reboot
	;;
    "int")
	[ "$gpumode" != "ECO" ] &&
	    yad --title="MUX-Steuerung" --text="\n Zum Ecomodus umschalten und neu starten? \n" &&
            rog-mux -s optimus &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.rules ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.disabled /etc/udev/rules.d/00-remove-nvidia.rules; } &&
	    xfce4-session-logout --reboot
	;;
    "ult")
	[ "$gpumode" != "ULT" ] &&
	    yad --title="MUX-Steuerung" --text="\n Zu Ultimate umschalten und neu starten? \n" &&
	    rog-mux -s ultimate &&
	    { [ -e /etc/udev/rules.d/00-remove-nvidia.disabled ] || \
		  sudo mv /etc/udev/rules.d/00-remove-nvidia.rules /etc/udev/rules.d/00-remove-nvidia.disabled; } &&
	    xfce4-session-logout --reboot
	;;
    *)
	echo "Parameters to choose are HYB|ECO|ULT"
	;;
esac
