#!/bin/bash
# ~/.local/share/gpu-install

# MANUAL INTERVENTION
#######################
# add visudo file

sudo cp ./gpu /usr/local/bin/gpu
sudo chown root:root /usr/local/bin/gpu
sudo chmod 755 /usr/local/bin/gpu
