#!/bin/bash
# /etc/kernel.d/post-install/70-sbctl

PKGNAME="$1"
VERSION="$2"

KERNEL_PATH="/boot/vmlinuz-${VERSION}"

if [ -f "$KERNEL_PATH" ]; then
    sbctl sign "$KERNEL_PATH"
fi

sbctl sign-all 2>/dev/null
