#!/bin/bash
# /etc/kernel.d/post-install/70-sbctl

PKGNAME="$1"
VERSION="$2"

sbctl sign-all 2>/dev/null

for mod in /lib/modules/"${VERSION}"/misc/vbox*.ko; do
    [ -e "$mod" ] || continue
    sbctl sign "$mod"
done
